### ISSUE TITLE
[docs] Step-by-step setup guide

### ISSUE THREAD

**Issue by gregfenton** [kafkas/firewalk#67]
I think it will make this code/project more accessible if you give a brief, step-by-step walkthru of creating a new NPM project, installing both firebase-admin and firewalk, adding the service account, and how to setup the project so that the code samples given work in the project.

The code samples will not work because of async/await unless you are using a newer version of NodeJS and/or you set `"type": "module"` in package.json.

**Comment by kafkas** [comment]
Thanks for the feedback and suggestions. Regarding the `"type": "module"`, it seems you're referring to the top-level `await` in the code samples. These samples are concise examples illustrating how to use the library within a project already set up for Firestore interaction. They assume that you have the necessary Firestore configuration in place to read from and write to Firestore. No additional configuration beyond what is typically required for Firestore integration is necessary.

This package is CommonJS, so you don't need to set `"type": "module"` in your package.json. The top-level `await` is used for simplicity in the examples, but you can easily incorporate the code samples by placing them within an appropriate function or class method etc.

That said, I may consider adding a comprehensive guide in the future to enhance accessibility although this is not a responsibility of this library.

**Comment by gregfenton** [comment]
Older versions of node do not support top-level async/await by default. So if there is a minimum version requirement to run the examples that could be added to the Readme or the package.json

**Comment by kafkas** [comment]
As explained above, top level await is not needed. You just need to place the sample code in some function or class method etc. Code samples are just small pieces of code that show a specific section of the file.
